import type { Metadata } from 'next'
import { Inter, Oxygen } from 'next/font/google'
import '@/styles/globals.css'
import { cn } from '@/lib/utils'
import { AppCartProvider } from '@/components/shop/app-cart-provider'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })
const oxygem = Oxygen({weight: ["300", "400", "700"], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Stripe Commerce',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(oxygem.className, "min-h-screen fle flex-col")}>
          <link rel="icon" href='./images/picture-profile-icon-male-icon-human-or-people-sign-and-symbol-vector.jpg'
          type='image/<generated>'
          sizes='<generated>' />
        <AppCartProvider>
          <Toaster />
          <main className=''>
            {children}
            </main>  
        </AppCartProvider>
        </body>
    </html>
  )
}
